[package]
name = "project_yer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
rowan = "0.10.0"
num-derive = "0.3.3"
num-traits = "0.2.14"

